name: gopher-social

services:
  db:
    image: postgres:18.3-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: gopher-social
      PGDATABASE: gopher-social
      POSTGRES_USER: admin
      PGUSER: admin
      POSTGRES_PASSWORD: adminpassword
      PGPASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgressql/data
    ports:
      - "5434:5432"

volumes:
  db-data:
